format_version: 9
common:
  build_stage: &build_stage
    - stage-build:
        jobs:
          job-build:
            resources:
              - msbuild
            tasks:
              - exec:
                  command: "cmd.exe"
                  arguments:
                  - "/c"
                  - toolbox\\make.cmd
              - exec:
                  command: "cmd.exe"
                  arguments:
                  - "/c"
                  - toolbox\\arcgis10_mapping_tools\\arcaddins_for_testing\\post_build_copy_addins.cmd
  testing_stage: &testing_stage
    - stage-test:
        jobs:
          job-test:
            artifacts:
              - test:
                  source: toolbox\\arcgis10_mapping_tools\\TestResult.xml
            tabs:
              unit-tests: toolbox\\arcgis10_mapping_tools\\TestResult.xml
              coverage: toolbox\\arcgis10_mapping_tools\\coverage\\index.htm
            tasks:
              - exec:
                  command: "cmd.exe"
                  arguments:
                  - "/c"
                  - toolbox\\arcgis10_mapping_tools\\get_coverage.cmd

pipelines:
  test-all-prs:
    group: MapAction-Toolbox
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      toolbox:
        scm: 232f5f9c-a656-49b3-b172-d6242cb1a3bc
        destination: toolbox
    stages:
      - *build_stage
      - *testing_stage
  deploy-master:
    group: MapAction-Toolbox
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      toolbox:
        git: https://github.com/mapaction/mapaction-toolbox.git
        destination: toolbox
        branch: master
        username: mapaction-ci-servers
        encrypted_password : AES:/tL+kSfanw1Vz+YhfX+C7g==:3UFicQJU9iJAH7ITgi/0MsBRs0Al81OIIkwq9Qru0NPsuXsTT+tFOtKAf4JhZXI7
    stages:
      - *build_stage
      - *testing_stage
