echo Building...
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe %~dp0arcgis10_mapping_tools/MapAction-toolbox.sln /t:build /p:PlatformTarget=x86 /p:Configuration=Release /maxcpucount

:: echo Copying...
:: call %~dp0arcgis10_mapping_tools\arcaddins_for_testing\post_build_copy_addins.cmd

:: echo Running Tests...
:: call %~dp0arcgis10_mapping_tools\get_coverage.cmd

