


Public Module DataNamingConstants
    Public Const DATANAME_UNKNOWN_STATUS = 0
    Public Const DATANAME_VALID = -1

    Public Const DATANAME_ERROR = 2
    Public Const DATANAME_WARN = 4
    Public Const DATANAME_INFO = 8

    Public Const DATANAME_ERROR_INVALID_GEOEXTENT = DATANAME_ERROR Or (2 ^ 4)
    Public Const DATANAME_ERROR_INVALID_DATACATEGORY = DATANAME_ERROR Or (2 ^ 5)
    Public Const DATANAME_ERROR_INVALID_DATATHEME = DATANAME_ERROR Or (2 ^ 6)
    Public Const DATANAME_ERROR_INVALID_DATATYPE = DATANAME_ERROR Or (2 ^ 7)
    Public Const DATANAME_ERROR_INCORRECT_DATATYPE = DATANAME_ERROR Or (2 ^ 8)
    Public Const DATANAME_ERROR_INCORRECT_SCALE = DATANAME_ERROR Or (2 ^ 8)
    Public Const DATANAME_ERROR_INCORRECT_SOURCE = DATANAME_ERROR Or (2 ^ 8)
    Public Const DATANAME_ERROR_INCORRECT_PERMISSIONS = DATANAME_ERROR Or (2 ^ 8)
    Public Const DATANAME_ERROR_OTHER_ERROR = DATANAME_ERROR Or (2 ^ 9)
    Public Const DATANAME_ERROR_CONTAINS_HYPHENS = DATANAME_ERROR Or (2 ^ 12)
    Public Const DATANAME_ERROR_TOO_FEW_CLAUSES = DATANAME_ERROR Or (2 ^ 13)

    Public Const DATANAME_WARN_MISSING_SCALE_CLAUSE = DATANAME_WARN Or (2 ^ 14)
    Public Const DATANAME_WARN_MISSING_PERMISSIONS_CLAUSE = DATANAME_WARN Or (2 ^ 15)
    Public Const DATANAME_WARN_TWO_CHAR_FREE_TEXT = DATANAME_WARN Or (2 ^ 16)  '_MAYBE_ERRONEOUS_PERMISSION_CLAUSE

    Public Const DATANAME_INFO_FREE_TEXT_PRESENT = DATANAME_INFO Or (2 ^ 17)

End Module
