//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapAction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapAction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;languageSettings&gt;
        ///   &lt;language name=&quot;English&quot;&gt;
        ///      &lt;language_label&gt;English&lt;/language_label&gt;   
        ///      &lt;create_date_time_label&gt;Created&lt;/create_date_time_label&gt;
        ///      &lt;data_sources_label&gt;&amp;lt;bol&amp;gt;Data Sources&amp;lt;/bol&amp;gt;&lt;/data_sources_label&gt;
        ///      &lt;mxd_name_label&gt;Map Document&lt;/mxd_name_label&gt;
        ///      &lt;spatial_reference_label&gt;Projection &amp;amp; Datum&lt;/spatial_reference_label&gt;
        ///      &lt;glide_no_label&gt;GLIDE Number&lt;/glide_no_label&gt;
        ///	  &lt;map_producer&gt;Produced by MapAct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string language_config {
            get {
                return ResourceManager.GetString("language_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;MapActionToolbarConfig&gt;
        ///  &lt;Tools&gt;
        ///    &lt;Tool&gt;
        ///      &lt;ToolName&gt;Operation Config Tool&lt;/ToolName&gt;
        ///      &lt;Components&gt;
        ///        &lt;Component&gt;
        ///          &lt;ComponentName&gt;Organisation Url&lt;/ComponentName&gt;
        ///          &lt;ComboBoxItems&gt;
        ///            &lt;ComboBoxItem&gt;
        ///              &lt;ComboBoxItemValue&gt;https://maps.mapaction.org/dataset/&lt;/ComboBoxItemValue&gt;
        ///            &lt;/ComboBoxItem&gt;
        ///            &lt;ComboBoxItem&gt;
        ///              &lt;ComboBoxItemValue&gt;https://maps-staging.mapaction.org/dataset/&lt;/ComboBoxItemValue&gt;
        ///            &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapActionToolbarsConfig {
            get {
                return ResourceManager.GetString("MapActionToolbarsConfig", resourceCulture);
            }
        }
    }
}
