' ---------------------------------------------------------------------------
' MyFirstModel.vbs
' Created on: Sun Nov 15 2009 07:24:37 PM
'   (generated by ArcGIS/ModelBuilder)
' ---------------------------------------------------------------------------

' Create the Geoprocessor object
set gp = WScript.CreateObject("esriGeoprocessing.GPDispatch.1")

' Load required toolboxes...
gp.AddToolbox "C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx"


' Local variables...
NestBuff = "D:\GettingToKnowArcGIS_CD\GTKArcGIS\Chapter20\MyData\MyTongass.mdb\NestBuff"
NestsF = "NestsF"

' Process: Buffer...
gp.Buffer_analysis NestsF, NestBuff, "800 Meters", "FULL", "ROUND", "ALL", ""

